services:
  # PostgreSQL database service
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: proshop
      POSTGRES_PASSWORD: Root4321
      POSTGRES_DB: proshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend service
  backend:
    image: backend:latest
    container_name: backend_service
    environment:
      DATABASE_URL: postgres://proshop:Root4321@db:5432/proshop
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  # Frontend service
  frontend:
    image: frontend:latest
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

