apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cHJvc2hvcA==         # 'proshop' base64 encoded
  POSTGRES_USER: cHJvc2hvcA==       # 'proshop' base64 encoded
  POSTGRES_PASSWORD: Um9vdDQzMjE=   # 'Root4321' base64 encoded

