apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  nfs:
    path: /mnt/volume
    server: 192.168.18.66
  persistentVolumeReclaimPolicy: Retain

